### PR TITLE
Add new option to expand the string given at VimuxPromptCommand.

### PR DESCRIPTION
**Pull request by jerri**
Unfortunately this is only a very simple approach. The expand()-function
in VimL is not very helpful.

### CODE REVIEW

**Review by alerque — APPROVED** [review]
Thanks for this contribution, and for the documentation too! Would you happen to be around to rebase this so it can be merged?

**Comment by jerri** [comment]
Sure. Can do.

**Comment by jerri** [comment]
Updated the code and tested it again. Should work now with the newest version of vimux.

**Review by alerque — APPROVED** [review]
Great! Thanks for getting this fixed up for the current code base.

**Pull request merged**
