### PR TITLE
Tab now autocompletes in the VimuxPromptOption

### PR DESCRIPTION
**Pull request by thalesmello**
This pull request changes the call to the input function in the `:VimuxPromptCommand` option so that pressing tab autocompletes, just as if it was in the terminal.

### CODE REVIEW

**Comment by pablobfonseca** [comment]
Looking forward to it 👍

**Comment by madchap** [comment]
Stumbled upon this, while it would be a welcome addition, it does seem to break some stuff, at least when I run VimRunLastCommand such as through:

```
map <Leader>vl :VimuxRunLastCommand<CR>
```

With command above and your change, it messes up with insert mode, my file content.

**Comment by alerque** [comment]
@madchap I am unable to replicate any issues with this like you describe and at least one other user also confirms it doesn't create problems. I'm going to go ahead and get this merged but feel free to open an issue if there is a problem.

**Review by alerque — APPROVED** [review]
Thanks for taking the time to contribute this!

**Pull request merged**
