### PR TITLE
Update CI workflows

### PR DESCRIPTION
**Pull request by mvanderkamp**
# Problem
The CI workflows are failing or not getting picked up by runners.

## Vint
Failing:
```
Run vint .
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.12.0/x64/bin/vint", line 5, in <module>
    from vint import main
  File "/opt/hostedtoolcache/Python/3.12.0/x64/lib/python3.12/site-packages/vint/__init__.py", line 1, in <module>
    from vint.bootstrap import (
  File "/opt/hostedtoolcache/Python/3.[12](https://github.com/preservim/vimux/actions/runs/6923608934/job/18831713393?pr=222#step:5:13).0/x64/lib/python3.12/site-packages/vint/bootstrap.py", line 5, in <module>
    from vint.linting.cli import CLI
  File "/opt/hostedtoolcache/Python/3.12.0/x64/lib/python3.12/site-packages/vint/linting/cli.py", line 4, in <module>
    import pkg_resources
ModuleNotFoundError: No module named 'pkg_resources'
Error: Process completed with exit code 1.
```

## Check
Not being picked up:
```
Requested labels: ubuntu-18.04
Job defined at: preservim/vimux/.github/workflows/check.yml@refs/pull/222/merge
Waiting for a runner to pick up this job...
```

# Solution
Let's try updating the actions.

### CODE REVIEW

**Comment by mvanderkamp** [comment]
I think the incomplete actions on this PR are the ones that are defined on `master`, since they include specific ubuntu versions in their matrix. They don't show up in the Actions tab though. My guess is, those checks are defined as required in the branch protections. @alerque are you able to check the settings?

Also is there a reason we specifically were testing on ubuntu 18?

**Comment by mvanderkamp** [comment]
@alerque Can you adjust the branch protections so that this repo isn't blocked waiting for checks that will never complete?

**Review by alerque — APPROVED** [review]

**Comment by alerque** [comment]
I don't know why this didn't land on my radar (I probably dismissed notifications too quickly in some batch) but thanks for the contribution. I'll check the required tests after this is in master and hence picked up by the required checks interface.

**Comment by mvanderkamp** [comment]
Thanks!

**Pull request merged**
